//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AMS.Models.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AMSEntities object using the connection string found in the 'AMSEntities' section of the application configuration file.
        /// </summary>
        public AMSEntities() : base("name=AMSEntities", "AMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AMSEntities object.
        /// </summary>
        public AMSEntities(string connectionString) : base(connectionString, "AMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AMSEntities object.
        /// </summary>
        public AMSEntities(EntityConnection connection) : base(connection, "AMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Account> Accounts
        {
            get
            {
                if ((_Accounts == null))
                {
                    _Accounts = base.CreateObjectSet<Account>("Accounts");
                }
                return _Accounts;
            }
        }
        private ObjectSet<Account> _Accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BannerInZone> BannerInZones
        {
            get
            {
                if ((_BannerInZones == null))
                {
                    _BannerInZones = base.CreateObjectSet<BannerInZone>("BannerInZones");
                }
                return _BannerInZones;
            }
        }
        private ObjectSet<BannerInZone> _BannerInZones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Banner> Banners
        {
            get
            {
                if ((_Banners == null))
                {
                    _Banners = base.CreateObjectSet<Banner>("Banners");
                }
                return _Banners;
            }
        }
        private ObjectSet<Banner> _Banners;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Campaign> Campaigns
        {
            get
            {
                if ((_Campaigns == null))
                {
                    _Campaigns = base.CreateObjectSet<Campaign>("Campaigns");
                }
                return _Campaigns;
            }
        }
        private ObjectSet<Campaign> _Campaigns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Module> Modules
        {
            get
            {
                if ((_Modules == null))
                {
                    _Modules = base.CreateObjectSet<Module>("Modules");
                }
                return _Modules;
            }
        }
        private ObjectSet<Module> _Modules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Page> Pages
        {
            get
            {
                if ((_Pages == null))
                {
                    _Pages = base.CreateObjectSet<Page>("Pages");
                }
                return _Pages;
            }
        }
        private ObjectSet<Page> _Pages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Permission> Permissions
        {
            get
            {
                if ((_Permissions == null))
                {
                    _Permissions = base.CreateObjectSet<Permission>("Permissions");
                }
                return _Permissions;
            }
        }
        private ObjectSet<Permission> _Permissions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Template> Templates
        {
            get
            {
                if ((_Templates == null))
                {
                    _Templates = base.CreateObjectSet<Template>("Templates");
                }
                return _Templates;
            }
        }
        private ObjectSet<Template> _Templates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserInRole> UserInRoles
        {
            get
            {
                if ((_UserInRoles == null))
                {
                    _UserInRoles = base.CreateObjectSet<UserInRole>("UserInRoles");
                }
                return _UserInRoles;
            }
        }
        private ObjectSet<UserInRole> _UserInRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Website> Websites
        {
            get
            {
                if ((_Websites == null))
                {
                    _Websites = base.CreateObjectSet<Website>("Websites");
                }
                return _Websites;
            }
        }
        private ObjectSet<Website> _Websites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Zone> Zones
        {
            get
            {
                if ((_Zones == null))
                {
                    _Zones = base.CreateObjectSet<Zone>("Zones");
                }
                return _Zones;
            }
        }
        private ObjectSet<Zone> _Zones;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccounts(Account account)
        {
            base.AddObject("Accounts", account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BannerInZones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBannerInZones(BannerInZone bannerInZone)
        {
            base.AddObject("BannerInZones", bannerInZone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Banners EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBanners(Banner banner)
        {
            base.AddObject("Banners", banner);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Campaigns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCampaigns(Campaign campaign)
        {
            base.AddObject("Campaigns", campaign);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModules(Module module)
        {
            base.AddObject("Modules", module);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPages(Page page)
        {
            base.AddObject("Pages", page);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Permissions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPermissions(Permission permission)
        {
            base.AddObject("Permissions", permission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Templates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemplates(Template template)
        {
            base.AddObject("Templates", template);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserInRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserInRoles(UserInRole userInRole)
        {
            base.AddObject("UserInRoles", userInRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Websites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWebsites(Website website)
        {
            base.AddObject("Websites", website);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Zones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZones(Zone zone)
        {
            base.AddObject("Zones", zone);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Account CreateAccount(global::System.Guid id)
        {
            Account account = new Account();
            account.ID = id;
            return account;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Guid> value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OTP
        {
            get
            {
                return _OTP;
            }
            set
            {
                OnOTPChanging(value);
                ReportPropertyChanging("OTP");
                _OTP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OTP");
                OnOTPChanged();
            }
        }
        private global::System.String _OTP;
        partial void OnOTPChanging(global::System.String value);
        partial void OnOTPChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Banner")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Banner : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Banner object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Banner CreateBanner(global::System.Guid id)
        {
            Banner banner = new Banner();
            banner.ID = id;
            return banner;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BannerName
        {
            get
            {
                return _BannerName;
            }
            set
            {
                OnBannerNameChanging(value);
                ReportPropertyChanging("BannerName");
                _BannerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BannerName");
                OnBannerNameChanged();
            }
        }
        private global::System.String _BannerName;
        partial void OnBannerNameChanging(global::System.String value);
        partial void OnBannerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BannerUrl
        {
            get
            {
                return _BannerUrl;
            }
            set
            {
                OnBannerUrlChanging(value);
                ReportPropertyChanging("BannerUrl");
                _BannerUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BannerUrl");
                OnBannerUrlChanged();
            }
        }
        private global::System.String _BannerUrl;
        partial void OnBannerUrlChanging(global::System.String value);
        partial void OnBannerUrlChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="BannerInZone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BannerInZone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BannerInZone object.
        /// </summary>
        /// <param name="bannerID">Initial value of the BannerID property.</param>
        /// <param name="zoneID">Initial value of the ZoneID property.</param>
        /// <param name="campaignID">Initial value of the CampaignID property.</param>
        public static BannerInZone CreateBannerInZone(global::System.Guid bannerID, global::System.Guid zoneID, global::System.Guid campaignID)
        {
            BannerInZone bannerInZone = new BannerInZone();
            bannerInZone.BannerID = bannerID;
            bannerInZone.ZoneID = zoneID;
            bannerInZone.CampaignID = campaignID;
            return bannerInZone;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid BannerID
        {
            get
            {
                return _BannerID;
            }
            set
            {
                if (_BannerID != value)
                {
                    OnBannerIDChanging(value);
                    ReportPropertyChanging("BannerID");
                    _BannerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BannerID");
                    OnBannerIDChanged();
                }
            }
        }
        private global::System.Guid _BannerID;
        partial void OnBannerIDChanging(global::System.Guid value);
        partial void OnBannerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ZoneID
        {
            get
            {
                return _ZoneID;
            }
            set
            {
                if (_ZoneID != value)
                {
                    OnZoneIDChanging(value);
                    ReportPropertyChanging("ZoneID");
                    _ZoneID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ZoneID");
                    OnZoneIDChanged();
                }
            }
        }
        private global::System.Guid _ZoneID;
        partial void OnZoneIDChanging(global::System.Guid value);
        partial void OnZoneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CampaignID
        {
            get
            {
                return _CampaignID;
            }
            set
            {
                if (_CampaignID != value)
                {
                    OnCampaignIDChanging(value);
                    ReportPropertyChanging("CampaignID");
                    _CampaignID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CampaignID");
                    OnCampaignIDChanged();
                }
            }
        }
        private global::System.Guid _CampaignID;
        partial void OnCampaignIDChanging(global::System.Guid value);
        partial void OnCampaignIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDateTime
        {
            get
            {
                return _StartDateTime;
            }
            set
            {
                OnStartDateTimeChanging(value);
                ReportPropertyChanging("StartDateTime");
                _StartDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDateTime");
                OnStartDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDateTime;
        partial void OnStartDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDateTime
        {
            get
            {
                return _EndDateTime;
            }
            set
            {
                OnEndDateTimeChanging(value);
                ReportPropertyChanging("EndDateTime");
                _EndDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDateTime");
                OnEndDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDateTime;
        partial void OnEndDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Campaign")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Campaign : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Campaign object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Campaign CreateCampaign(global::System.Guid id)
        {
            Campaign campaign = new Campaign();
            campaign.ID = id;
            return campaign;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CampaignName
        {
            get
            {
                return _CampaignName;
            }
            set
            {
                OnCampaignNameChanging(value);
                ReportPropertyChanging("CampaignName");
                _CampaignName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CampaignName");
                OnCampaignNameChanged();
            }
        }
        private global::System.String _CampaignName;
        partial void OnCampaignNameChanging(global::System.String value);
        partial void OnCampaignNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDateTime
        {
            get
            {
                return _StartDateTime;
            }
            set
            {
                OnStartDateTimeChanging(value);
                ReportPropertyChanging("StartDateTime");
                _StartDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDateTime");
                OnStartDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDateTime;
        partial void OnStartDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDateTime
        {
            get
            {
                return _EndDateTime;
            }
            set
            {
                OnEndDateTimeChanging(value);
                ReportPropertyChanging("EndDateTime");
                _EndDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDateTime");
                OnEndDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDateTime;
        partial void OnEndDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Module : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Module object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Module CreateModule(global::System.Guid id)
        {
            Module module = new Module();
            module.ID = id;
            return module;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Guid> value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ControllerCode
        {
            get
            {
                return _ControllerCode;
            }
            set
            {
                OnControllerCodeChanging(value);
                ReportPropertyChanging("ControllerCode");
                _ControllerCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ControllerCode");
                OnControllerCodeChanged();
            }
        }
        private global::System.String _ControllerCode;
        partial void OnControllerCodeChanging(global::System.String value);
        partial void OnControllerCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionCode
        {
            get
            {
                return _ActionCode;
            }
            set
            {
                OnActionCodeChanging(value);
                ReportPropertyChanging("ActionCode");
                _ActionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionCode");
                OnActionCodeChanged();
            }
        }
        private global::System.String _ActionCode;
        partial void OnActionCodeChanging(global::System.String value);
        partial void OnActionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parameters
        {
            get
            {
                return _Parameters;
            }
            set
            {
                OnParametersChanging(value);
                ReportPropertyChanging("Parameters");
                _Parameters = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Parameters");
                OnParametersChanged();
            }
        }
        private global::System.String _Parameters;
        partial void OnParametersChanging(global::System.String value);
        partial void OnParametersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModuleName
        {
            get
            {
                return _ModuleName;
            }
            set
            {
                OnModuleNameChanging(value);
                ReportPropertyChanging("ModuleName");
                _ModuleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModuleName");
                OnModuleNameChanged();
            }
        }
        private global::System.String _ModuleName;
        partial void OnModuleNameChanging(global::System.String value);
        partial void OnModuleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModuleType
        {
            get
            {
                return _ModuleType;
            }
            set
            {
                OnModuleTypeChanging(value);
                ReportPropertyChanging("ModuleType");
                _ModuleType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleType");
                OnModuleTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _ModuleType;
        partial void OnModuleTypeChanging(Nullable<global::System.Int32> value);
        partial void OnModuleTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ShowInMenu
        {
            get
            {
                return _ShowInMenu;
            }
            set
            {
                OnShowInMenuChanging(value);
                ReportPropertyChanging("ShowInMenu");
                _ShowInMenu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowInMenu");
                OnShowInMenuChanged();
            }
        }
        private Nullable<global::System.Boolean> _ShowInMenu;
        partial void OnShowInMenuChanging(Nullable<global::System.Boolean> value);
        partial void OnShowInMenuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortIndex
        {
            get
            {
                return _SortIndex;
            }
            set
            {
                OnSortIndexChanging(value);
                ReportPropertyChanging("SortIndex");
                _SortIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortIndex");
                OnSortIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _SortIndex;
        partial void OnSortIndexChanging(Nullable<global::System.Int32> value);
        partial void OnSortIndexChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Page")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Page : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Page object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Page CreatePage(global::System.Guid id)
        {
            Page page = new Page();
            page.ID = id;
            return page;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> WebsiteID
        {
            get
            {
                return _WebsiteID;
            }
            set
            {
                OnWebsiteIDChanging(value);
                ReportPropertyChanging("WebsiteID");
                _WebsiteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebsiteID");
                OnWebsiteIDChanged();
            }
        }
        private Nullable<global::System.Guid> _WebsiteID;
        partial void OnWebsiteIDChanging(Nullable<global::System.Guid> value);
        partial void OnWebsiteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PageName
        {
            get
            {
                return _PageName;
            }
            set
            {
                OnPageNameChanging(value);
                ReportPropertyChanging("PageName");
                _PageName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PageName");
                OnPageNameChanged();
            }
        }
        private global::System.String _PageName;
        partial void OnPageNameChanging(global::System.String value);
        partial void OnPageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PageUrl
        {
            get
            {
                return _PageUrl;
            }
            set
            {
                OnPageUrlChanging(value);
                ReportPropertyChanging("PageUrl");
                _PageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PageUrl");
                OnPageUrlChanged();
            }
        }
        private global::System.String _PageUrl;
        partial void OnPageUrlChanging(global::System.String value);
        partial void OnPageUrlChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Permission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Permission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Permission object.
        /// </summary>
        /// <param name="accountID">Initial value of the AccountID property.</param>
        /// <param name="moduleID">Initial value of the ModuleID property.</param>
        /// <param name="accountType">Initial value of the AccountType property.</param>
        public static Permission CreatePermission(global::System.Guid accountID, global::System.Guid moduleID, global::System.Int32 accountType)
        {
            Permission permission = new Permission();
            permission.AccountID = accountID;
            permission.ModuleID = moduleID;
            permission.AccountType = accountType;
            return permission;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AccountID
        {
            get
            {
                return _AccountID;
            }
            set
            {
                if (_AccountID != value)
                {
                    OnAccountIDChanging(value);
                    ReportPropertyChanging("AccountID");
                    _AccountID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AccountID");
                    OnAccountIDChanged();
                }
            }
        }
        private global::System.Guid _AccountID;
        partial void OnAccountIDChanging(global::System.Guid value);
        partial void OnAccountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                if (_ModuleID != value)
                {
                    OnModuleIDChanging(value);
                    ReportPropertyChanging("ModuleID");
                    _ModuleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModuleID");
                    OnModuleIDChanged();
                }
            }
        }
        private global::System.Guid _ModuleID;
        partial void OnModuleIDChanging(global::System.Guid value);
        partial void OnModuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountType
        {
            get
            {
                return _AccountType;
            }
            set
            {
                if (_AccountType != value)
                {
                    OnAccountTypeChanging(value);
                    ReportPropertyChanging("AccountType");
                    _AccountType = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AccountType");
                    OnAccountTypeChanged();
                }
            }
        }
        private global::System.Int32 _AccountType;
        partial void OnAccountTypeChanging(global::System.Int32 value);
        partial void OnAccountTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> FullControl
        {
            get
            {
                return _FullControl;
            }
            set
            {
                OnFullControlChanging(value);
                ReportPropertyChanging("FullControl");
                _FullControl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FullControl");
                OnFullControlChanged();
            }
        }
        private Nullable<global::System.Boolean> _FullControl;
        partial void OnFullControlChanging(Nullable<global::System.Boolean> value);
        partial void OnFullControlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Changeable
        {
            get
            {
                return _Changeable;
            }
            set
            {
                OnChangeableChanging(value);
                ReportPropertyChanging("Changeable");
                _Changeable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Changeable");
                OnChangeableChanged();
            }
        }
        private Nullable<global::System.Boolean> _Changeable;
        partial void OnChangeableChanging(Nullable<global::System.Boolean> value);
        partial void OnChangeableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ReadOnly
        {
            get
            {
                return _ReadOnly;
            }
            set
            {
                OnReadOnlyChanging(value);
                ReportPropertyChanging("ReadOnly");
                _ReadOnly = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadOnly");
                OnReadOnlyChanged();
            }
        }
        private Nullable<global::System.Boolean> _ReadOnly;
        partial void OnReadOnlyChanging(Nullable<global::System.Boolean> value);
        partial void OnReadOnlyChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Role CreateRole(global::System.Guid id)
        {
            Role role = new Role();
            role.ID = id;
            return role;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Template")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Template : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Template object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Template CreateTemplate(global::System.Guid id)
        {
            Template template = new Template();
            template.ID = id;
            return template;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TemplateName
        {
            get
            {
                return _TemplateName;
            }
            set
            {
                OnTemplateNameChanging(value);
                ReportPropertyChanging("TemplateName");
                _TemplateName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TemplateName");
                OnTemplateNameChanged();
            }
        }
        private global::System.String _TemplateName;
        partial void OnTemplateNameChanging(global::System.String value);
        partial void OnTemplateNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TemplateContent
        {
            get
            {
                return _TemplateContent;
            }
            set
            {
                OnTemplateContentChanging(value);
                ReportPropertyChanging("TemplateContent");
                _TemplateContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TemplateContent");
                OnTemplateContentChanged();
            }
        }
        private global::System.String _TemplateContent;
        partial void OnTemplateContentChanging(global::System.String value);
        partial void OnTemplateContentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="UserInRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserInRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserInRole object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="roleID">Initial value of the RoleID property.</param>
        public static UserInRole CreateUserInRole(global::System.Guid userID, global::System.Guid roleID)
        {
            UserInRole userInRole = new UserInRole();
            userInRole.UserID = userID;
            userInRole.RoleID = roleID;
            return userInRole;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Guid _UserID;
        partial void OnUserIDChanging(global::System.Guid value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Guid _RoleID;
        partial void OnRoleIDChanging(global::System.Guid value);
        partial void OnRoleIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Website")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Website : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Website object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Website CreateWebsite(global::System.Guid id)
        {
            Website website = new Website();
            website.ID = id;
            return website;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebsiteName
        {
            get
            {
                return _WebsiteName;
            }
            set
            {
                OnWebsiteNameChanging(value);
                ReportPropertyChanging("WebsiteName");
                _WebsiteName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebsiteName");
                OnWebsiteNameChanged();
            }
        }
        private global::System.String _WebsiteName;
        partial void OnWebsiteNameChanging(global::System.String value);
        partial void OnWebsiteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebsiteUrl
        {
            get
            {
                return _WebsiteUrl;
            }
            set
            {
                OnWebsiteUrlChanging(value);
                ReportPropertyChanging("WebsiteUrl");
                _WebsiteUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebsiteUrl");
                OnWebsiteUrlChanged();
            }
        }
        private global::System.String _WebsiteUrl;
        partial void OnWebsiteUrlChanging(global::System.String value);
        partial void OnWebsiteUrlChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Zone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Zone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Zone object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Zone CreateZone(global::System.Guid id)
        {
            Zone zone = new Zone();
            zone.ID = id;
            return zone;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> PageID
        {
            get
            {
                return _PageID;
            }
            set
            {
                OnPageIDChanging(value);
                ReportPropertyChanging("PageID");
                _PageID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageID");
                OnPageIDChanged();
            }
        }
        private Nullable<global::System.Guid> _PageID;
        partial void OnPageIDChanging(Nullable<global::System.Guid> value);
        partial void OnPageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZoneName
        {
            get
            {
                return _ZoneName;
            }
            set
            {
                OnZoneNameChanging(value);
                ReportPropertyChanging("ZoneName");
                _ZoneName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZoneName");
                OnZoneNameChanged();
            }
        }
        private global::System.String _ZoneName;
        partial void OnZoneNameChanging(global::System.String value);
        partial void OnZoneNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Double> _Width;
        partial void OnWidthChanging(Nullable<global::System.Double> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Double> _Height;
        partial void OnHeightChanging(Nullable<global::System.Double> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> TemplateID
        {
            get
            {
                return _TemplateID;
            }
            set
            {
                OnTemplateIDChanging(value);
                ReportPropertyChanging("TemplateID");
                _TemplateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TemplateID");
                OnTemplateIDChanged();
            }
        }
        private Nullable<global::System.Guid> _TemplateID;
        partial void OnTemplateIDChanging(Nullable<global::System.Guid> value);
        partial void OnTemplateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContainerID
        {
            get
            {
                return _ContainerID;
            }
            set
            {
                OnContainerIDChanging(value);
                ReportPropertyChanging("ContainerID");
                _ContainerID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContainerID");
                OnContainerIDChanged();
            }
        }
        private global::System.String _ContainerID;
        partial void OnContainerIDChanging(global::System.String value);
        partial void OnContainerIDChanged();

        #endregion

    
    }

    #endregion

    
}
